// // // import { Geist, Geist_Mono } from "next/font/google";

// // // import "./globals.css";
// // // import Sidebar from "./components/Sidebar";
// // // import RightSidebar from "./components/RightSidebar";
// // // import SessionWrapper from "./SessionWrapper";
// // // import Navbar from "./components/Navbar";
// // // import { AuthProvider } from "./context/page";

// // // const geistSans = Geist({
// // //   variable: "--font-geist-sans",
// // //   subsets: ["latin"],
// // // });

// // // const geistMono = Geist_Mono({
// // //   variable: "--font-geist-mono",
// // //   subsets: ["latin"],
// // // });

// // // export const metadata = {
// // //   title: "Create Next App",
// // //   description: "Generated by create next app",
// // // };

// // // export default function RootLayout({ children, modal }) {
// // //   return (
// // //     <html lang="en" className="scroll-smooth">
// // //       <head>
// // //         <link
// // //           rel="stylesheet"
// // //           href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400;500;700&display=swap"
// // //         />
// // //       </head>
// // //       <body className={`${geistSans.variable} ${geistMono.variable}`}>
// // //         <SessionWrapper>
// // //           <AuthProvider>
// // //             <Navbar />

// // //             <div className="flex pt-16 min-h-screen w-full">
// // //               {/* Sidebar */}
// // //               <aside className="w-[240px] fixed top-16 left-0 h-[calc(100vh-64px)] border-r bg-white z-10">
// // //                 <Sidebar />
// // //               </aside>

// // //               {/* Main content (Masonry grid area) */}
// // //               <main className="ml-[240px] w-full px-4 md:px-8 py-6">
// // //                 {children}
// // //               </main>
// // //             </div>

// // //             {/* Optional Modal */}
// // //             {modal}
// // //           </AuthProvider>
// // //         </SessionWrapper>

// // //         {/* Footer */}
// // //         <footer className="border-t p-8 text-center mt-16 text-dark ml-[240px]">
// // //           &copy; 2023 All rights reserved
// // //         </footer>
// // //       </body>
// // //     </html>
// // //   );
// // // }
// // import { Geist, Geist_Mono } from "next/font/google";
// // import "./globals.css";
// // import Sidebar from "./components/Sidebar";
// // import RightSidebar from "./components/RightSidebar";
// // import SessionWrapper from "./SessionWrapper";
// // import Navbar from "./components/Navbar";
// // import { AuthProvider } from "./context/page";

// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// // export const metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({ children, modal }: { children: React.ReactNode; modal: React.ReactNode }) {
// //   return (
// //     <html lang="en" className="scroll-smooth">
// //       <head>
// //         <link
// //           rel="stylesheet"
// //           href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400;500;700&display=swap"
// //         />
// //       </head>
// //       <body className={`${geistSans.variable} ${geistMono.variable}`}>
// //         <SessionWrapper>
// //           <AuthProvider>
// //             <Navbar />

// //             <div className="flex pt-16 min-h-screen w-full">
// //               {/* Left Sidebar - hidden on mobile */}
// //               <aside className="hidden md:fixed md:block md:w-[240px] md:top-16 md:left-0 md:h-[calc(100vh-64px)] md:border-r md:bg-white z-10">
// //                 <Sidebar />
// //               </aside>

// //               {/* Main Content - shifted on md+ */}
// //               <main className="w-full px-4 md:ml-[240px] md:px-8 py-6">
// //                 {children}
// //               </main>
// //             </div>

// //             {modal}
// //           </AuthProvider>
// //         </SessionWrapper>

// //         {/* Footer - also shifted on md+ */}
// //         <footer className="border-t p-8 text-center mt-16 text-dark md:ml-[240px]">
// //           &copy; 2023 All rights reserved
// //         </footer>
// //       </body>
// //     </html>
// //   );
// // }
// import { Geist, Geist_Mono } from "next/font/google";

// import "./globals.css";
// import Sidebar from "./components/Sidebar";
// import RightSidebar from "./components/RightSidebar";
// import SessionWrapper from "./SessionWrapper";
// import Navbar from "./components/Navbar";
// import { AuthProvider } from "./context/page";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children, modal }) {
//   return (
//     <html lang="en" className="scroll-smooth">
//       <head>
//         <link
//           rel="stylesheet"
//           href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400;500;700&display=swap"
//         />
//       </head>
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         <SessionWrapper>
//           <AuthProvider>
//             <Navbar />

//             <div className="flex pt-16 min-h-screen w-full">
//               {/* Sidebar - hidden on mobile */}
//               <aside className="hidden md:block w-[240px] fixed top-16 left-0 h-[calc(100vh-64px)] border-r bg-white z-10">
//                 <Sidebar />
//               </aside>

//               {/* Main content - shifts right on md screens */}
//               <main className="w-full px-4 md:px-8 py-6 md:ml-[240px]">
//                 {children}
//               </main>
//             </div>

//             {/* Optional Modal */}
//             {modal}
//           </AuthProvider>
//         </SessionWrapper>

//         {/* Footer */}
//         <footer className="border-t p-8 text-center mt-16 text-dark md:ml-[240px]">
//           &copy; 2023 All rights reserved
//         </footer>
//       </body>
//     </html>
//   );
// }
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import Sidebar from "./components/Sidebar";
import SessionWrapper from "./SessionWrapper";
import Navbar from "./components/Navbar";
import { AuthProvider } from "./context/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, modal }) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400;500;700&display=swap"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <SessionWrapper>
          <AuthProvider>
            <Navbar />

            {/* Main Layout */}
            <div className="flex pt-12 min-h-screen w-full">
              {/* Sidebar */}
              <aside className="hidden md:block w-[240px] fixed top-12 left-0 h-[calc(100vh-48px)] border-r bg-white z-10">
                <Sidebar />
              </aside>

              {/* Main Content */}
              <main className="w-full px-4 md:px-6 py-4 md:ml-[240px]">
                {children}
              </main>
            </div>

            {/* Optional Modal */}
            {modal}
          </AuthProvider>
        </SessionWrapper>

        {/* Footer */}
        <footer className="border-t p-6 text-center text-dark md:ml-[240px]">
          &copy; 2023 All rights reserved
        </footer>
      </body>
    </html>
  );
}
